# -*- coding: utf-8 -*-
"""inference.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1cglK9b1z49tEjVkkM6eZbKWcv-02EHOc
"""

from google.colab import drive
drive.mount('/content/gdrive')

# Commented out IPython magic to ensure Python compatibility.
# %cd gdrive/MyDrive/project

# Install python libraries
!pip install -r requirements.txt
!pip install 'git+https://github.com/cocodataset/cocoapi.git#subdirectory=PythonAPI'

# Install detectron2
!python setup.py build develop

from image import *
import cv2
IMG_FILE = "./COCO_train2014_000000150367.jpg"

cfg_file = "configs/VG-Detection/faster_rcnn_R_101_C4_caffemaxpool_wrapper.yaml"

im = cv2.imread(IMG_FILE)
model = FasterRCNNBottomUp(cfg_file)
boxes = model(im)

torch.save(boxes, "boxes.pt")